/*
 * OS.h
 *
 *  Created on: Jun 4, 2022
 *      Author: szuperpeti
 */

#ifndef INC_OS_H_
#define INC_OS_H_
#include "main.h"

			/*Macros*/
#define OVERFLOW_DETECTION_SIZE (5u)
#define MIN_STACK_SIZE			(16u + OVERFLOW_DETECTION_SIZE)
#define MAX_THREADS 			(5u)







			/*Global Variables*/
typedef struct
{
	uint32_t *stack_pointer;
	struct TCB *next;
	uint8_t *thread_ID;
	uint8_t *first_function_ID;
	uint8_t *second_function_ID;
	uint8_t *third_function_ID;
}TCB;



extern TCB *current_thread_pt;


			/*Function declarations*/
void CreateThread(void (*thread_handler)(void), uint32_t stack_size,
												uint32_t *stack_ptr,
												uint8_t *thread_id,
												uint8_t *function1,
												uint8_t *function2,
												uint8_t *function3);
void halt_us(volatile uint32_t time);
void halt_ms(volatile uint32_t time);
void Blink1(void);
void Blink2(void);

void Os_Init(void);

void System_Fault_Handler(uint8_t *string);






#define NOP_US __asm(  			\
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
);

#define NOP_MS __asm(			\
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
			"nop\n"             \
);



#endif /* INC_OS_H_ */
